name: soilmaster
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  build_runner: ^2.3.3
  cached_network_image: null
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  fl_chart: ^0.63.0
  flutter_timezone: ^1.0.6

  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_local_notifications: ^15.1.0+1
  flutter_riverpod: ^2.3.6
  flutter_slidable: ^3.0.0
  flutterfire_ui: ^0.4.3+20
  freezed: ^2.3.3
  freezed_annotation: ^2.2.0
  google_sign_in: ^5.2.1
  http: ^0.13.6
  intl: any
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  lottie: ^2.3.2
  permission_handler: ^10.2.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0
  shimmer: ^2.0.0
  showcaseview: ^2.0.3
  simple_gradient_text: 1.2.4
  syncfusion_flutter_charts: ^21.2.3
  url_launcher: ^6.1.10
  velocity_x: any

dev_dependencies:
  custom_lint: 0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.2.3
  riverpod_lint: 1.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/weatherassets/
    - assets/icons/
    - assets/imgs/

  fonts:
    - family: Gol
      fonts:
        - asset: assets/fonts/Trade Gothic LT Light.ttf

    - family: Go
      fonts:
        - asset: assets/fonts/Trade Gothic LT.ttf
